language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - cp php/app/config/parameters.yml.dist php/app/config/parameters.yml
  - cd php/ && composer install

script: phpunit -c php/app/
