aa_EuroMillions_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AAEuroMillionsBundle:Default:index }

AAEuroMillionsBundle_aa_draw:
    resource: "@AAEuroMillionsBundle/Resources/config/routing/draw.yml"
    prefix:   /draw
