homepage:
    pattern:  /
    defaults: { _controller: ArturAlvesEuroMillionsBundle:Dashboard:index }

draws:
    pattern:  /draws
    defaults: { _controller: ArturAlvesEuroMillionsBundle:Draw:index }

# ArturAlvesEuroMillionsBundle_aa_draw:
#     resource: "@ArturAlvesEuroMillionsBundle/Resources/config/routing/draw.yml"
#     prefix:   /draw
