services:
    # artur_alves_euro_millions.rules:
    #     class: ArturAlves\EuroMillionsBundle\Model\Rules
    #     arguments: ['@service_container']

    validator.unique.draw_validator:
        class: ArturAlves\EuroMillionsBundle\Validator\Constraints\ObeysTheRulesValidator
        arguments: ['@service_container']
        tags:
            - { name: validator.constraint_validator, alias: ObeysTheRulesValidator }
